### ISSUE TITLE
Is Python 3.10 really the minimum compatible version?

### ISSUE THREAD

**Issue by fdabrandao** [nextmv-io/nextmv-py#17]
Would it be possible to make this package available for Python 3.9? I am tying to install it on Streamlit Cloud but it runs 3.9.18 and the only nextmv version compatible seems to be 0.0.1.

**Comment by sebastian-quintero** [comment]
Hey! The reason why `3.10` is required is because of the `|` (pipe) operator used in type hints introduced in `3.10` ([link](https://devguide.python.org/versions/#supported-versions)). I’ll look into using older Python constructs for the type hints where we use the pipe operator. I think this wouldn’t break anyone, as long as you are passing the correct types where appropriate.

**Comment by cnpryer** [comment]
You should be able to provide compatibility with older versions by importing `annotations` from `__future__`.

```py
from __future__ import annotations
```

**Comment by sebastian-quintero** [comment]
We conducted some tests and determined that we could modify the type hints to match older constructs without affecting newer versions. Plan is to support the minimum available Python version (3.8) until it reaches the end of its shelf life.

**Comment by fdabrandao** [comment]
Thanks for fixing this so quickly! I have just tested it with requirement `nextmv @ git+https://github.com/nextmv-io/nextmv-py@bbd330e` on Streamlit Cloud and it works.

**Comment by sebastian-quintero** [comment]
@fdabrandao We released version `v0.5.0`, you should be able to use it with python `>=3.8`. Thanks.
